### ISSUE TITLE
Wrong version deployed as 2.3.3 on NuGet.org

### ISSUE THREAD

**Issue by JoakimKSS** [alexmcbride/insimdotnet#21]
The IS_MAL packet is missing from the version available on Nuget.org. However it is still marked as version 2.3.3.

Should implement this latest commit and re-release on NuGet.org:
https://github.com/on3pixel/insimdotnet-1

**Comment by alexmcbride** [comment]
I don't maintain this any more really, except for merging PRs. Someone is free to upload their own NuGet package with a better version. I can always remove my old one if that happens.

**Comment by alexmcbride** [comment]
Updated Nuget package to the latest version
